### ISSUE TITLE
Upgraded system and Gateway, systemd unit failing to start

### ISSUE THREAD

**Issue by typh289** [WebThingsIO/gateway-aur#4]
Hi, after updating both the system (Arch linux) and rebuilding the gateway from AUR, i got issues starting again the service,
the only error i can find on logs is:

 webthings-gateway[2271]: setpriv: libcap-ng is too old for "all" caps

Anyone may have some hints to help me fix this?

**Comment by mrstegeman** [comment]
Maybe try installing `libcap` rather than `libcap-ng`.

**Comment by mrstegeman** [comment]
Well, maybe not. Those appear to be entirely different.

**Comment by typh289** [comment]
Looks like the flag -all is not accepted on the setpriv launch command anymore for some reason i couldn't figure out, temporarily fixed by modifying the launcher with a comma separated list of the capabilities to remove instead of -all, will update if i find a solution

**Comment by rshadow** [comment]
same problem with deb package

**Comment by mrstegeman** [comment]
According to the Debian manpages, `--inh-caps=-all` should be valid: https://manpages.debian.org/buster/util-linux/setpriv.1.en.html

**Comment by mrstegeman** [comment]
@typh289 what's the change you ended up having to make? Can you post it here so I can patch things?

**Comment by typh289** [comment]
Sorry i didn't notice this, yes i'll update with how i modified when i get home but basically listed all the caps and removed them with a comma separated list instead of a -all flag

update:
--inh-caps=-chown,-dac_override,-dac_read_search,-fowner,-fsetid,-kill,-setgid,-setuid,-setpcap,-linux_immutable,-net_bind_service,-net_broadcast,-net_admin,-net_raw,-ipc_lock,-ipc_owner,-sys_module,-sys_rawio,-sys_chroot,-sys_ptrace,-sys_pacct,-sys_admin,-sys_boot,-sys_nice,-sys_resource,-sys_time,-sys_tty_config,-mknod,-lease,-audit_write,-audit_control,-setfcfcap,-mac_override,-mac_admin,-syslog,-wake_alarm,-block_suspend,-audit_read,-cap_38,-cap_39 \

instead of --inh-caps=-all in /usr/bin/webthings-gateway, definitely doesn't look right but made it start and didn't bother yet to look better at it

**Comment by eCompassion** [comment]
Which file was modified or what package changes were needed to resolve the libffi6 / libffi7?

**Comment by mrstegeman** [comment]
@eCompassion https://github.com/WebThingsIO/gateway/commit/b0592a6144c3241feb5f8d150b8a93def58a2413
