### ISSUE TITLE
Custom icons upload fails

### ISSUE THREAD

**Issue by typh289** [WebThingsIO/gateway-aur#6]
Got this error while trying to upload some new icons
ERROR  : Failed to write icon: Error: template option must be relative to "/tmp", found "/etc/webthings-gateway/uploads/XXXXXX.svg".

@mrstegeman i found a forum thread where you mentioned this was fixed already, may you point me in the right direction?

**Comment by mrstegeman** [comment]
https://github.com/WebThingsIO/gateway/pull/2675

**Comment by typh289** [comment]
ty! somehow i didn't see that commit
